### ISSUE TITLE
Revised Core cards don't have artists

### ISSUE THREAD

**Issue by SpencerDub** [Alsciende/netrunner-cards-json#313]
It appears that none of the cards from the Revised Core have artists listed in their data. Is there a reason for this, or is it just an oversight?

**Comment by gereons** [comment]
I believe they were intentionally left out when the RCS was announced, because we only had a card list and knew that new art was coming, but not precisely by which artists and for which cards.

Since the release of the RCS no one has yet found the time to update this info, a PR for this would be welcome!

**Comment by gereons** [comment]
added in #318 
Thanks!
